Modified Flows
latchbio-nfcore/atacseq pull request #1
Opened 2024-08-20 18:26 UTC by hsmurali

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/atacseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-30 22:12 UTC, hsmurali commented
I have updated the workflow to
1. Interface workflow output to make data for plots
2. Made registry tables to be pulled into plots
3. Added documentation for the workflow

Could you please leave comments to this commit, [31a1cbe](https://github.com/latchbio-nfcore/atacseq/pull/1/commits/31a1cbe2b558e955583aba308d38184771c126a2)?

2024-09-05 23:26 UTC, tahirdme requested changes

2024-09-05 23:26 UTC, tahirdme commented on latch_metadata/__init__.py
>          name="Your Name",
change to "nf-core" - we have a cool new graphic

2024-09-05 23:26 UTC, tahirdme commented on latch_metadata/__init__.py
> +                "Latch Certified Reference Genome", Params("genome")
You should call this latch_genome

We should still allow people to use iGenomes if they want honestly 
So call this "latch_genome" and leave a "genome" in the Hidden Options for optional iGenomes - might be handy for us in a fix

2024-09-05 23:26 UTC, tahirdme commented on wf/entrypoint.py
> +    shutil.copy(bamfile.local_path, str(Path().resolve()))
Confused about the .copy() here which is followed by the .download() a few lines below

2024-09-05 23:26 UTC, tahirdme commented on wf/entrypoint.py
> +            splits = Path(s).name.split(".")
Can you confirm that wrapping a LPath().path link in a Path object won't download it

2024-09-05 23:26 UTC, tahirdme commented on wf/entrypoint.py
> -from dataclasses import dataclass
Can you add function level descriptions to your code?

Hard to figure out what each function is supposed to be doing 

With this under the def()
"""
exampleexampleexampleexample
""""

2024-09-05 23:26 UTC, tahirdme commented on wf/entrypoint.py
> -from dataclasses import dataclass
Would also recommend splitting up the nextflow entrypoint from the Registry and postprocessing code in separate .py files

Makes it easier to read and understand

2024-09-13 23:54 UTC, hsmurali reviewed
@tahirdme I have tested the launch plans, it works fine and I also added the igenomes back. I have also changed the s3 links with the test dataset.

2024-09-14 20:08 UTC, merged